# Generated by Django 4.1.7 on 2023-02-27 10:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("store", "0003_add_slug_to_product"),
    ]

    operations = [
        migrations.AddField(
            model_name="address",
            name="zip",
            field=models.CharField(default="exit", max_length=6),
            preserve_default=False,
        ),
    ]
